### PR TITLE
Pinned cloudbuild maven image to maven:3.6-jdk-8

### PR DESCRIPTION
**Pull request by itzg**
Fixing deploy failure where Java 8 (class file version 52.0) ended up trying run code compiled with Java 11 (class file version 55.0):

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/rackspacecloud/metrics/queryservice/QueryServiceApplication has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

### CODE REVIEW

**Review by shawnashlee — DISMISSED** [review]

**Comment by shawnashlee** [comment]
actually, its giving this error in the build:
```
Fatal error compiling: invalid target release: 11 -> [Help 1]
```

**Comment by itzg** [comment]
Ugh, the pom is self-contracting

https://github.com/racker/ceres-query-service/blob/2be7bd41c97d557a578fd1a69df81f40413101dd/pom.xml#L24

https://github.com/racker/ceres-query-service/blob/2be7bd41c97d557a578fd1a69df81f40413101dd/pom.xml#L126

ok...I guess I'll pin it to Java 11 and reconcile those compiler versions

**Comment by itzg** [comment]
@jjbuchan @GeorgeJahad @harageth , sorry for all the whitespace change -- the inconsistent indentation finally got to me. You can exclude the final commit to ignore that or use the whitespace option in the "files changed" view.

**Comment by itzg** [comment]
...fyi, the default base image used by jib is not pinned to any particular version

https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#from-object

**Review by jjbuchan — APPROVED** [review]

**Pull request merged**
